<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FUJITSU-PC" name="com.vmetry.ntltaxi.testcases.HomePageTest" tests="1" failures="0" timestamp="26 Sep 2016 03:40:39 GMT" time="0.000" errors="1">
  <testcase name="validateHomepage" time="0.000" classname="com.vmetry.ntltaxi.testcases.HomePageTest">
    <error type="java.lang.RuntimeException" message="java.io.FileNotFoundException: \Users\vinothkumar\Documents\SeleniumWorkspace\web\smita\DDFramework\src\main\java\com\vmetry\ntltaxi\inputreader\inputcontroller.xlsx (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: \Users\vinothkumar\Documents\SeleniumWorkspace\web\smita\DDFramework\src\main\java\com\vmetry\ntltaxi\inputreader\inputcontroller.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1287)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1004)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1093)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.io.FileNotFoundException: \Users\vinothkumar\Documents\SeleniumWorkspace\web\smita\DDFramework\src\main\java\com\vmetry\ntltaxi\inputreader\inputcontroller.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.vmetry.ntltaxi.inputreader.inputReader.RunModeVerification(inputReader.java:22)
	at com.vmetry.ntltaxi.testcases.HomePageTest.getHomePageData(HomePageTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 20 more
]]>
    </error>
  </testcase> <!-- validateHomepage -->
</testsuite> <!-- com.vmetry.ntltaxi.testcases.HomePageTest -->
